language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7

#branches:
#  only:
#    - master
#    # Build maintenance branches for older releases if needed. such branches should be named like "1.2"
#    - '/^\d+\.\d+$/'

install:
  - composer update $COMPOSER_FLAGS --prefer-source --no-interaction

script:
  - phpunit --coverage-clover=coverage.clover
